# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-raspberrypi4-64-custom"
BBFILE_PATTERN_meta-raspberrypi4-64-custom = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-raspberrypi4-64-custom = "6"

LAYERDEPENDS_meta-raspberrypi4-64-custom = "core"

LAYERSERIES_COMPAT_meta-raspberrypi4-64-custom = "kirkstone"

