MACHINE = "raspberrypi4-64"
DISTRO = "poky"

# Enable SSH and Wi-Fi
IMAGE_FEATURES += "ssh-server-openssh"
IMAGE_INSTALL:append = " wpa-supplicant wireless-tools wpa-supplicant-config"

# Clean up work directory after each recipe is built
INHERIT += "rm_work"

# Specify where to find the custom layer
BBPATH .= ":${TOPDIR}/../metas-propias/meta-raspberrypi4-64-custom"

# Package management
PACKAGE_CLASSES = "package_rpm"

# Connect to the internet
CONNECTIVITY_CHECK_URIS = "https://www.google.com/"

#parallelism options
BB_NUMBER_THREADS = "4"
PARALLEL_MAKE = "-j 4"

# Set the path to the download directory
DL_DIR = "${TOPDIR}/../downloads"

# Set the path to the sstate cache directory
SSTATE_DIR = "${TOPDIR}/../sstate-cache"

# Set the path to the cache directory
CACHE = "${TOPDIR}/../cache"

# Add license for wpa_supplicant
LICENSE_FLAGS_ACCEPTED = "commercial"
