# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rpi-custom"
BBFILE_PATTERN_rpi-custom = "^${LAYERDIR}/"
BBFILE_PRIORITY_rpi-custom = "10"

LAYERDEPENDS_rpi-custom = "core"

LAYERSERIES_COMPAT_rpi-custom = "kirkstone"
